# NAME: Quentin Truong
# EMAIL: quentintruong@gmail.com
# ID: 404782322

.SILENT:

default:
	-rm -f lab3b
	ln lab3b.py lab3b
	chmod 777 lab3b

dist:
	tar -czf lab3b-404782322.tar.gz Makefile README lab3b.py

clean:
	rm -f lab3b lab3b-404782322.tar.gz
