# NAME: Quentin Truong
# EMAIL: quentintruong@gmail.com
# ID: 404782322

.SILENT:

CC = gcc
FLAGS = -Wall -Wextra

default:
	$(CC) $(FLAGS) lab1a.c -o lab1a

clean:
	rm -f lab1a lab1a-404782322.tar.gz

dist:
	tar -czf lab1a-404782322.tar.gz lab1a.c Makefile README
